Revert "chore: polish async code more"
This reverts commit 4e1ce913f83c7637557cd9a56e0e43c422628984.

`mypy` was complaining:

```
tests/async/test_dialog.py:57: error: "append" of "list" does not return a value
tests/async/test_dialog.py:67: error: "append" of "list" does not return a value
tests/async/test_dialog.py:77: error: "append" of "list" does not return a value
```